import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="mn">
      <body className="flex">
        {/* Sidebar хэсэг */}
        <Sidebar />

        {/* Үндсэн контент (Sidebar-ийн өргөнийг хасаад үлдсэн зайг авна) */}
        <main className="ml-64 p-8 w-full min-h-screen bg-gray-50 text-black">
          {children}
        </main>
      </body>
    </html>
  );
}
